version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MONGO_HOST=db
      - MONGO_PORT=27017

  db:
    image: mongo  
    ports:
      - "27017:27017"  
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
